#ifndef __APP_HAL_H
#define __APP_HAL_H

#include "debug.h"
#include <stdbool.h>
#include <stdint.h>

/*
 * Board-level hardware definitions.
 *
 * This file is the single source of truth for application-owned pins and
 * timing constants. The peripheral drivers consume these macros instead of
 * embedding GPIO numbers in their implementation files.
 */
#define APP_BUTTON_PORT      GPIOA
#define APP_BUTTON_PIN       GPIO_Pin_1
#define APP_BUTTON_PRESSED   Bit_RESET

/* USART1 is reserved for serial firmware update / IAP bootloader traffic. */
#define APP_IAP_USART                USART1
#define APP_IAP_USART_CLK_APB2       RCC_APB2Periph_USART1
#define APP_IAP_GPIO_PORT            GPIOA
#define APP_IAP_GPIO_CLK_APB2        RCC_APB2Periph_GPIOA
#define APP_IAP_TX_PIN               GPIO_Pin_9
#define APP_IAP_RX_PIN               GPIO_Pin_10
#define APP_IAP_BAUDRATE             115200U

/* USART3 is the application command and telemetry port. */
#define APP_CMD_USART                USART3
#define APP_CMD_USART_CLK_APB1       RCC_APB1Periph_USART3
#define APP_CMD_USART_IRQn           USART3_IRQn
#define APP_CMD_GPIO_PORT            GPIOB
#define APP_CMD_GPIO_CLK_APB2        RCC_APB2Periph_GPIOB
#define APP_CMD_TX_PIN               GPIO_Pin_10
#define APP_CMD_RX_PIN               GPIO_Pin_11
#define APP_CMD_BAUDRATE             115200U
#define APP_CMD_RX_BUF_SIZE          256U
#define APP_PROTOCOL_RX_BUDGET       64U

/*
 * Linear CCD wiring.
 * AO is sampled by ADC1; SI and CLK are ordinary GPIO signals generated by
 * the capture routine. One capture produces APP_CCD_PIXEL_COUNT samples.
 */
#define APP_CCD_AO_PORT               GPIOA
#define APP_CCD_AO_PIN                GPIO_Pin_4
#define APP_CCD_AO_ADC_CHANNEL        ADC_Channel_4
#define APP_CCD_CLK_PORT              GPIOB
#define APP_CCD_CLK_PIN               GPIO_Pin_3
#define APP_CCD_SI_PORT               GPIOA
#define APP_CCD_SI_PIN                GPIO_Pin_2
#define APP_CCD_PIXEL_COUNT           128U
#define APP_CCD_SAMPLE_PERIOD_MS      50U
#define APP_CCD_MIN_CONTRAST          8U
#define APP_CCD_SERIAL_TEST           0U
#define APP_CCD_SERIAL_TEST_PERIOD_MS 200U

/*
 * Servo PWM plan: TIM3 CH1..CH4 drive the four leg servos.
 * The former tail-servo channel is intentionally no longer part of the
 * firmware model. Pulses use the conventional 20 ms servo period.
 */
#define APP_SERVO_COUNT              4U
#define APP_SERVO_MIN_US             500U
#define APP_SERVO_MAX_US             2500U
#define APP_SERVO_NEUTRAL_US         1500U
#define APP_SERVO_PERIOD_US          20000U

#define APP_SERVO_TIM3_CLK_APB1      RCC_APB1Periph_TIM3
#define APP_SERVO_GPIOA_CLK_APB2     RCC_APB2Periph_GPIOA
#define APP_SERVO_GPIOB_CLK_APB2     RCC_APB2Periph_GPIOB

#define APP_SERVO_TIM3_CH1_PIN       GPIO_Pin_6
#define APP_SERVO_TIM3_CH2_PIN       GPIO_Pin_7
#define APP_SERVO_TIM3_CH3_PIN       GPIO_Pin_0
#define APP_SERVO_TIM3_CH4_PIN       GPIO_Pin_1

/* Passive buzzer PWM: PA8 / TIM1_CH1. */
#define APP_BUZZER_GPIO_PORT         GPIOA
#define APP_BUZZER_GPIO_CLK_APB2     RCC_APB2Periph_GPIOA
#define APP_BUZZER_TIM_CLK_APB2      RCC_APB2Periph_TIM1
#define APP_BUZZER_PIN               GPIO_Pin_8
#define APP_BUZZER_PWM_FREQ_HZ       2000U
#define APP_BUZZER_BEEP_MS           500U

/* Active-low status LED: PB8. The application toggles it every 500 ms. */
#define APP_STATUS_LED_PORT          GPIOB
#define APP_STATUS_LED_GPIO_CLK_APB2 RCC_APB2Periph_GPIOB
#define APP_STATUS_LED_PIN           GPIO_Pin_8
#define APP_STATUS_LED_ACTIVE_LOW    1U
#define APP_STATUS_LED_TOGGLE_MS     500U

/* SSD1306 OLED: PB6/PB7 are hardware I2C1 SCL/SDA. */
#define APP_OLED_I2C_PORT            GPIOB
#define APP_OLED_I2C_GPIO_CLK_APB2   RCC_APB2Periph_GPIOB
#define APP_OLED_I2C_CLK_APB1        RCC_APB1Periph_I2C1
#define APP_OLED_I2C_SCL_PIN         GPIO_Pin_6
#define APP_OLED_I2C_SDA_PIN         GPIO_Pin_7
#define APP_OLED_I2C_ADDR_7BIT       0x3CU
#define APP_OLED_REFRESH_MS          1000U

#define APP_CMD_LINE_MAX             160U

/* Phase-1 software constants. */
#define APP_DEBOUNCE_MS      20U
#define APP_BOOT_MS          1000U
#define APP_LED_BOOT_MS      100U
#define APP_LED_IDLE_MS      500U
#define APP_LED_ACTIVE_MS    150U

typedef struct
{
    BitAction stable_level;
    BitAction last_sample;
    uint16_t stable_count_ms;
} button_debounce_t;

#endif /* __APP_HAL_H */
