export type WorkbenchRoute =
  | 'course-center'
  | 'course-tasks'
  | 'code'
  | 'build'
  | 'review'
  | 'flash'
  | 'resources'
  | 'settings'
  | 'line-parameters'
  | 'ccd'
  | 'serial'
  | 'wch-link'
