#ifndef STUDENT_CONFIG_GENERATED_H
#define STUDENT_CONFIG_GENERATED_H

#define STUDENT_CONFIG_TURN_STRENGTH 18U
#define STUDENT_CONFIG_LINE_TARGET 64U

#if (STUDENT_CONFIG_TURN_STRENGTH < 1U) || (STUDENT_CONFIG_TURN_STRENGTH > 30U)
#error "STUDENT_CONFIG_TURN_STRENGTH must be in range 1..30"
#endif

#if (STUDENT_CONFIG_LINE_TARGET > 127U)
#error "STUDENT_CONFIG_LINE_TARGET must be in range 0..127"
#endif

#endif /* STUDENT_CONFIG_GENERATED_H */
